import React from 'react';
import dbConnect from '@/lib/dbConnect';
import ContentCollection from '@/models/ContentCollection';
import Content from '@/models/Content';
import { Download, FileIcon, Shield, Database, Clock } from 'lucide-react';

export const revalidate = 0; // Disable caching to fetch live public files on load

export default async function HomePage() {
  await dbConnect();

  // Find public, non-expired collections
  const publicCollections = await ContentCollection.find({
    isPublic: true,
    publicExpiresAt: { $gt: new Date() }
  }).sort({ createdAt: -1 }).lean();

  const collectionsWithFiles = await Promise.all(
    publicCollections.map(async (col) => {
      const files = await Content.find({ contentCollectionId: col._id }).sort({ createdAt: -1 }).lean();
      return {
        id: col._id.toString(),
        name: col.name || 'Public Share',
        expiresAt: col.publicExpiresAt ? new Date(col.publicExpiresAt) : null,
        files: files.map(file => ({
          id: file._id.toString(),
          name: file.originalName,
          size: file.size,
          mimeType: file.mimeType
        }))
      };
    })
  );

  const formatBytes = (bytes: number) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  const hasPublicFiles = collectionsWithFiles.some(c => c.files.length > 0);

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 flex flex-col justify-between">
      {/* Navigation */}
      <nav className="bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 px-6 py-4 shadow-sm">
        <div className="max-w-6xl mx-auto flex justify-between items-center">
          <div className="flex items-center gap-2">
            <Shield className="h-6 w-6 text-blue-600 animate-pulse" />
            <span className="font-bold tracking-tight">Core Storage Share</span>
          </div>
          <a
            href="/admin"
            className="text-xs bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 px-3.5 py-2 rounded-lg font-semibold transition"
          >
            Admin Panel
          </a>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-4xl w-full mx-auto p-6 flex-grow flex flex-col justify-center py-12">
        {!hasPublicFiles ? (
          /* Landing Screen when no Public Collections exist */
          <div className="text-center space-y-4 max-w-md mx-auto">
            <div className="inline-flex p-4 bg-blue-50 dark:bg-blue-950/20 text-blue-600 rounded-full">
              <Database className="h-8 w-8" />
            </div>
            <h1 className="text-2xl font-bold tracking-tight">Secure Private Storage</h1>
            <p className="text-sm text-slate-500 dark:text-slate-400">
              This node is operating in private sharing mode. Files can only be accessed using unique, encrypted transfer links generated by the system administrator.
            </p>
          </div>
        ) : (
          /* Public Download Lists */
          <div className="space-y-8">
            <div className="text-center md:text-left">
              <h1 className="text-2xl font-bold tracking-tight">Active Public Assets</h1>
              <p className="text-sm text-slate-500 mt-1">
                The collections below have been authorized for temporary public access.
              </p>
            </div>

            <div className="space-y-6">
              {collectionsWithFiles.map((col) => {
                if (col.files.length === 0) return null;
                return (
                  <div key={col.id} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden shadow-sm">
                    {/* Folder Header */}
                    <div className="bg-slate-50 dark:bg-slate-800/50 px-6 py-4 border-b border-slate-100 dark:border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                      <h3 className="font-bold text-slate-900 dark:text-slate-100">{col.name}</h3>
                      {col.expiresAt && (
                        <span className="flex items-center gap-1 text-[11px] text-yellow-600 font-semibold">
                          <Clock className="h-3 w-3" />
                          Expires: {col.expiresAt.toLocaleString()}
                        </span>
                      )}
                    </div>

                    {/* Files List */}
                    <div className="divide-y divide-slate-100 dark:divide-slate-800">
                      {col.files.map((file) => (
                        <div key={file.id} className="px-6 py-4 flex items-center justify-between gap-4">
                          <div className="flex items-center gap-3 min-w-0">
                            <FileIcon className="h-8 w-8 text-blue-500 shrink-0" />
                            <div className="min-w-0">
                              <p className="text-sm font-medium truncate text-slate-950 dark:text-slate-50">
                                {file.name}
                              </p>
                              <p className="text-xs text-slate-500">{formatBytes(file.size)}</p>
                            </div>
                          </div>
                          <a
                            href={`/api/download/${file.id}`}
                            className="flex items-center gap-1 bg-blue-600 hover:bg-blue-700 text-white px-3.5 py-2 rounded-lg text-xs font-semibold transition"
                          >
                            <Download className="h-3.5 w-3.5" />
                            Download
                          </a>
                        </div>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="text-center py-6 text-xs text-slate-400 border-t border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900">
        <p>© {new Date().getFullYear()} Core Storage Node. All Transfers Stream Encrypted.</p>
      </footer>
    </div>
  );
}